steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/matomo:${_VERSION}-${_VARIANT}', '-f', '${_VARIANT}/Dockerfile', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/matomo:${_VERSION}-${_VARIANT}']
substitutions:
    _VARIANT: "fpm-alpine"
    _VERSION: "4.1.1"
    