version: "3"

services:
  db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - ./db.env

  app:
    image: t3nde/matomo:dev
    restart: always
    depends_on:
      - db
    volumes:
      # - ./config/common.config.ini.php:/var/www/html/config/common.config.ini.php
      # - ./logs:/var/www/html/logs
      - matomo:/data
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./db.env
    ports:
      - 8088:80

volumes:
  db:
  matomo:
